version: '3'

services:
  # Servicio de MySQL
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: nico
      MYSQL_PASSWORD: CURSO2022
      MYSQL_DATABASE: ClinicaDentistadb
      MYSQL_ROOT_PASSWORD: CURSO2022
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  # Servicio de Tomcat
  tomcat:
    image: tomcat:9.0.75-jdk8-corretto-al2
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./web:/usr/local/tomcat/webapps:Z
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    links:
      - mysql:mysql

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: nico
      PMA_PASSWORD: CURSO2022

volumes:
  db_data:
    driver: local
